# Generic ML Pipeline Configuration Template
# This configuration can be adapted for any ML project

# Project identification
project_name: "cmci_competitiveness"  # Change this for your project
experiment_name: "production_models_v1"  # Version your experiments

# Data processing configuration
data_config:
  processor_class: "src.data.processors.CMCIDataProcessor"  # Your data processor class
  raw_data_path: "data/raw/cmci_data.csv"
  preprocessing:
    missing_value_strategy: "fillna"
    feature_selection: true
    normalize: true
  splitting:
    test_size: 0.2
    validation_size: 0.2
    random_state: 42
    stratify: true

# Models configuration - add/remove models as needed
models_config:
  random_forest:
    trainer_class: "src.models.trainers.RandomForestTrainer"
    hyperparameters:
      n_estimators: 100
      max_depth: 10
      random_state: 42
      n_jobs: -1
    
  gradient_boost:
    trainer_class: "src.models.trainers.GradientBoostTrainer"
    hyperparameters:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 6
      random_state: 42
  
  neural_network:
    trainer_class: "src.models.trainers.NeuralNetworkTrainer"
    hyperparameters:
      hidden_layers: [100, 50]
      learning_rate: 0.001
      epochs: 100
      batch_size: 32

# Evaluation configuration
evaluation_config:
  evaluator_class: "src.evaluation.evaluators.ClassificationEvaluator"
  primary_metric: "f1_score"  # Used for best model selection
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
    - "roc_auc"
  generate_plots:
    - "confusion_matrix"
    - "roc_curve"
    - "feature_importance"
    - "learning_curves"

# MLflow configuration
mlflow_config:
  tracking_uri: "http://localhost:5000"  # Override with MLFLOW_TRACKING_URI env var
  # registry_uri: "sqlite:///mlflow_registry.db"  # Optional separate registry
  auto_log: true
  log_models: true
  
# Logging configuration
logging_config:
  level: "INFO"
  log_dir: "logs"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Pipeline behavior
pipeline_config:
  fail_fast: false  # Continue with other models if one fails
  parallel_training: false  # Enable for concurrent model training
  save_intermediate_results: true
  cleanup_artifacts: false 