# Demo Configuration for Generic ML Pipeline
project_name: "competitiveness_demo"
experiment_name: "demo_run_v1"

# Data processing configuration
data_config:
  processor_class: "data.processors.CMCIDataProcessor"
  raw_data_path: "demo/data/sample_competitiveness_data.csv"
  preprocessing:
    missing_value_strategy: "fillna"
    feature_selection: true
    normalize: true
  splitting:
    test_size: 0.2
    validation_size: 0.2
    random_state: 42
    stratify: true

# Models configuration
models_config:
  random_forest:
    trainer_class: "models.trainers.RandomForestTrainer"
    hyperparameters:
      n_estimators: 50  # Smaller for demo speed
      max_depth: 8
      random_state: 42
      n_jobs: -1
    
  logistic_regression:
    trainer_class: "models.trainers.LogisticRegressionTrainer"
    hyperparameters:
      C: 1.0
      max_iter: 1000
      random_state: 42
  
  gradient_boost:
    trainer_class: "models.trainers.GradientBoostTrainer"
    hyperparameters:
      n_estimators: 50  # Smaller for demo speed
      learning_rate: 0.1
      max_depth: 6
      random_state: 42

# Evaluation configuration
evaluation_config:
  evaluator_class: "evaluation.evaluators.ClassificationEvaluator"
  primary_metric: "f1_score"
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
    - "roc_auc"
  generate_plots:
    - "confusion_matrix"
    - "roc_curve"
    - "feature_importance"
    - "learning_curves"

# MLflow configuration
mlflow_config:
  tracking_uri: "http://localhost:8080"
  auto_log: true
  log_models: true
  
# Logging configuration
logging_config:
  level: "INFO"
  log_dir: "demo/logs"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
